// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaitcrGtN2IWftfH1zG96P302edy1_Tl4',
    appId: '1:955278987042:web:99dbd6deb7f1868bf99f7b',
    messagingSenderId: '955278987042',
    projectId: 'detection-ai-image--and-voice',
    authDomain: 'detection-ai-image--and-voice.firebaseapp.com',
    storageBucket: 'detection-ai-image--and-voice.firebasestorage.app',
    measurementId: 'G-SH7JVGJ3J6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC552Luk9Knd9QpFO3eY_QEE1itRmLTISA',
    appId: '1:955278987042:android:1178b83aefc1278bf99f7b',
    messagingSenderId: '955278987042',
    projectId: 'detection-ai-image--and-voice',
    storageBucket: 'detection-ai-image--and-voice.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARfzgWzIidlRkAQPM1zUpwkLaVSeJr4z8',
    appId: '1:955278987042:ios:d1a62aaf295234e1f99f7b',
    messagingSenderId: '955278987042',
    projectId: 'detection-ai-image--and-voice',
    storageBucket: 'detection-ai-image--and-voice.firebasestorage.app',
    iosBundleId: 'com.example.appAiTraiter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARfzgWzIidlRkAQPM1zUpwkLaVSeJr4z8',
    appId: '1:955278987042:ios:d1a62aaf295234e1f99f7b',
    messagingSenderId: '955278987042',
    projectId: 'detection-ai-image--and-voice',
    storageBucket: 'detection-ai-image--and-voice.firebasestorage.app',
    iosBundleId: 'com.example.appAiTraiter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaitcrGtN2IWftfH1zG96P302edy1_Tl4',
    appId: '1:955278987042:web:18cc8245ad51334ff99f7b',
    messagingSenderId: '955278987042',
    projectId: 'detection-ai-image--and-voice',
    authDomain: 'detection-ai-image--and-voice.firebaseapp.com',
    storageBucket: 'detection-ai-image--and-voice.firebasestorage.app',
    measurementId: 'G-QY5B5WH9WK',
  );
}
